Repository Sinabro-littlebylittle/sinabroClient, pull requests merged in 2023-02, with the labels that each got.

#43 [fix]: koyeb 배포로 인한 retrofit baseUrl 변경 (#42)
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/git_toolbox_prj.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/render.experimental.xml
  .idea/vcs.xml
  app/src/main/java/com/project/sinabro/retrofit/RetrofitService.java
Labels: 🛠 FIX

#47 [fix]: Fragment 파일 중 Activity로 잘못 명명된 파일 및 코드 수정 (#46)
  app/src/main/java/com/project/sinabro/sideBarMenu/aboutUs/AboutUsFragment.java
  app/src/main/java/com/project/sinabro/sideBarMenu/bookmark/BookmarkAdapter.java
  app/src/main/java/com/project/sinabro/sideBarMenu/bookmark/BookmarkFragment.java
  app/src/main/java/com/project/sinabro/sideBarMenu/bookmark/Dictionary.java
  app/src/main/java/com/project/sinabro/sideBarMenu/myPage/MyPageFragment.java
  app/src/main/java/com/project/sinabro/sideBarMenu/settings/NotificationFragment.java
  app/src/main/java/com/project/sinabro/sideBarMenu/settings/SettingsFragment.java
  app/src/main/java/com/project/sinabro/sideBarMenu/settings/UsePolicyFragment.java
  app/src/main/java/com/project/sinabro/sideBarMenu/support/SupportFragment.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_about_us_activity.xml
  app/src/main/res/layout/fragment_bookmark_activity.xml
  app/src/main/res/layout/fragment_my_page_activity.xml
  app/src/main/res/layout/fragment_settings_activity.xml
  app/src/main/res/layout/fragment_settings_notification.xml
  app/src/main/res/layout/fragment_settings_use_policy.xml
  app/src/main/res/layout/fragment_support_activity.xml
  app/src/main/res/layout/settings_language_change.xml
  app/src/main/res/menu/navigation_menu.xml
  app/src/main/res/navigation/sidebar.xml
  app/src/main/res/values/strings.xml
Labels: 🛠 FIX

#48 [feat]: 장소 등록 UI 액티비티 추가 #25
  .idea/deploymentTargetDropDown.xml
  .idea/render.experimental.xml
  app/build.gradle
  app/src/debug/res/drawable/info.xml
  app/src/debug/res/drawable/location_pin.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project/sinabro/MainActivity.java
  app/src/main/java/com/project/sinabro/bottomSheet/place/AddLocationInfoActivity.java
  app/src/main/java/com/project/sinabro/bottomSheet/place/AddPlaceGuideActivity.java
  app/src/main/java/com/project/sinabro/bottomSheet/place/PlaceItem.java
  app/src/main/java/com/project/sinabro/bottomSheet/place/PlaceListActivity.java
  app/src/main/res/drawable-v24/people_scan.xml
  app/src/main/res/drawable/arrow_right.xml
  app/src/main/res/drawable/back.xml
  app/src/main/res/drawable/bottom_sheet_minus_bar.xml
  app/src/main/res/drawable/close.xml
  app/src/main/res/drawable/cursor_color.xml
  app/src/main/res/drawable/default_profile_image.jpg
  app/src/main/res/drawable/dialog_radius.xml
  app/src/main/res/drawable/edt_bg_normal.xml
  app/src/main/res/drawable/edt_bg_selected.xml
  app/src/main/res/drawable/edt_bg_selector.xml
  app/src/main/res/drawable/layout_container.xml
  app/src/main/res/drawable/people_count_list_view_item_background.xml
  app/src/main/res/drawable/person.xml
  app/src/main/res/drawable/radius_2.xml
  app/src/main/res/layout/activity_add_location_info.xml
  app/src/main/res/layout/activity_add_place_guide.xml
  app/src/main/res/layout/activity_place_list.xml
  app/src/main/res/layout/bottom_sheet.xml
  app/src/main/res/layout/dialog_place_info.xml
  app/src/main/res/layout/dialog_place_remove.xml
  app/src/main/res/layout/layout_navigation_header.xml
  app/src/main/res/layout/place_list_view_item.xml
  app/src/main/res/values-v24/styles.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: ⚙ FEAT, 💄 UI/UX

#51 [feat]: 세팅화면에서 알림설정 화면으로 넘어가는 기능 구현 #50
  .idea/.gitignore
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project/sinabro/sideBarMenu/settings/NotificationActivity.java
  app/src/main/java/com/project/sinabro/sideBarMenu/settings/NotificationFragment.java
  app/src/main/java/com/project/sinabro/sideBarMenu/settings/SettingsFragment.java
  app/src/main/res/layout/activity_settings_notification.xml
Labels: ⚙ FEAT, 💄 UI/UX

#57 [feat]: 문의 메뉴 클릭 시 (시나브로) 공용 메일로 메일 작성 기능 추가 (#56)
  app/src/main/java/com/project/sinabro/MainActivity.java
  app/src/main/java/com/project/sinabro/sideBarMenu/support/SupportFragment.java
  app/src/main/res/layout/fragment_support_activity.xml
Labels: ⚙ FEAT, 🛠 FIX

#59 [feat]: Sidebar Navigation 내 "개발 정보" 메뉴 액티비티 설계 (#58)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project/sinabro/MainActivity.java
  app/src/main/java/com/project/sinabro/sideBarMenu/devInfo/DevInfoFragment.java
  app/src/main/java/com/project/sinabro/sideBarMenu/devInfo/OpenSourceLicense.java
  app/src/main/java/com/project/sinabro/sideBarMenu/support/SupportFragment.java
  app/src/main/res/drawable/arrow_right_blue.xml
  app/src/main/res/drawable/arrow_right_grey.xml
  app/src/main/res/drawable/edt_bg_normal.xml
  app/src/main/res/drawable/goal_image.jpg
  app/src/main/res/drawable/small_info_background.xml
  app/src/main/res/drawable/underline.xml
  app/src/main/res/layout/activity_add_location_info.xml
  app/src/main/res/layout/activity_open_source_license.xml
  app/src/main/res/layout/fragment_about_us_activity.xml
  app/src/main/res/layout/fragment_dev_info_activity.xml
  app/src/main/res/layout/layout_navigation_header.xml
  app/src/main/res/layout/place_list_view_item.xml
  app/src/main/res/navigation/sidebar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ⚙ FEAT, 💄 UI/UX
