Repository Sinabro-littlebylittle/sinabroClient, pull requests merged in 2023-08, with the labels that each got.

#88 [fix]: JWT 인증 방식 도입으로 인한 기존 서버 APIs 엔드포인트 일부 수정 (#86)
  app/build.gradle
  app/src/main/java/com/project/sinabro/retrofit/PlacesAPI.java
  app/src/main/java/com/project/sinabro/retrofit/headcountsAPI.java
Labels: 🛠 FIX

#90 [feat]: `user_infos` collection 관련 APIs interface 및 model 파일 추가 (#89)
  app/src/main/java/com/project/sinabro/models/UserInfo.java
  app/src/main/java/com/project/sinabro/models/requests/ChangePasswordRequest.java
  app/src/main/java/com/project/sinabro/retrofit/UserAPI.java
Labels: ⚙ FEAT

#92 [feat]: `auth` router 관련 APIs interface 파일 추가 (#91)
  app/src/main/java/com/project/sinabro/models/requests/LoginRequest.java
  app/src/main/java/com/project/sinabro/retrofit/AuthAPI.java
Labels: ⚙ FEAT

#97 [feat]: 로그인 기능 추가 (#96)
  app/src/main/java/com/project/sinabro/MainActivity.java
  app/src/main/java/com/project/sinabro/bottomSheet/place/AddLocationInfoActivity.java
  app/src/main/java/com/project/sinabro/retrofit/RetrofitService.java
  app/src/main/java/com/project/sinabro/sideBarMenu/authentication/SignInActivity.java
  app/src/main/res/layout/activity_modify_my_info.xml
  app/src/main/res/values/string_account.xml
Labels: ⚙ FEAT

#99 [feat]: 이메일 중복 확인 기능 추가 (#98)
  app/src/main/java/com/project/sinabro/sideBarMenu/authentication/SignUpStep1Activity.java
  app/src/main/java/com/project/sinabro/sideBarMenu/settings/ModifyMyInfoActivity.java
Labels: ⚙ FEAT

#101 [feat]: 회원가입 기능 추가 (#100)
  app/src/main/java/com/project/sinabro/sideBarMenu/authentication/SignUpStep2Activity.java
Labels: ⚙ FEAT

#103 [feat]: 비밀번호 확인 액티비티 내 API 기능 추가 (#102)
  app/src/main/java/com/project/sinabro/sideBarMenu/settings/CheckPasswordActivity.java
  app/src/main/java/com/project/sinabro/sideBarMenu/settings/SettingsFragment.java
Labels: ⚙ FEAT

#105 [feat]: '비밀번호 변경 기능 추가' (#104)
  app/src/main/java/com/project/sinabro/sideBarMenu/settings/ModifyPasswordActivity.java
Labels: ⚙ FEAT

#109 Fix/108
  app/src/main/java/com/project/sinabro/bottomSheet/place/PlaceListActivity.java
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/fragment_settings_activity.xml
  app/src/main/res/layout/layout_navigation_header.xml
Labels: 🛠 FIX, 💄 UI/UX

#111 [fix]: 비밀번호 입력란 최소 입력 허용 글자수 에러 수정 (#110)
  app/src/main/java/com/project/sinabro/textWatcher/PasswordWatcher.java
Labels: 🛠 FIX

#114 [feat]: 카카오맵 서비스 영역 외 장소에 대한 스캔, 즐겨찾기 등록/취소 버튼 클릭 시 서비스 불가 지역 안내 메시지 추가 (#113)
  app/src/main/java/com/project/sinabro/MainActivity.java
Labels: ⚙ FEAT

#115 [fix]: Bottom Sheet 레이아웃 관련 액티비티 내부 APIs 호출 코드 내 로그인 시간 만료에 대한 예외 처리 코드 추가 (#112)
  app/src/main/java/com/project/sinabro/MainActivity.java
  app/src/main/java/com/project/sinabro/bottomSheet/place/AddLocationInfoActivity.java
  app/src/main/java/com/project/sinabro/bottomSheet/place/PlaceListActivity.java
  app/src/main/java/com/project/sinabro/sideBarMenu/bookmark/PlaceInListActivity.java
Labels: 🛠 FIX

#117 [fix]: 장소 삭제 API 스펙 변경으로 인한 클라이언트 측 코드 수정 (#116)
  app/src/main/java/com/project/sinabro/bottomSheet/place/AddLocationInfoActivity.java
  app/src/main/java/com/project/sinabro/retrofit/PlacesAPI.java
Labels: 🛠 FIX

#119 [fix]: 기존 people_numbers collection명 변경으로 인한 기존 해당 model 파일, API 인터페이스 및 관련 코드 일괄 수정 (#118)
  app/src/main/java/com/project/sinabro/MainActivity.java
  app/src/main/java/com/project/sinabro/bottomSheet/place/PlaceListActivity.java
  app/src/main/java/com/project/sinabro/models/Headcount.java
  app/src/main/java/com/project/sinabro/retrofit/headcountsAPI.java
Labels: 🛠 FIX

#121 [feat]: Kakao Developers APIs 사용으로 인한 앱 REST API 키 환경 변수 입력 라인 추가 (#120)
  gradle.properties
Labels: ⚙ FEAT

#127 [FEAT] 영상 업로드 및 분석을 위한 로딩화면 추가(#126)
  app/build.gradle
  app/src/main/java/com/project/sinabro/ALoadingDialog.java
  app/src/main/java/com/project/sinabro/ObjectDetectionActivity.kt
  app/src/main/res/layout/dialog_loading_layout.xml
  app/src/main/res/raw/loading.json
Labels: ⚙ FEAT

#129 [feat]: 인원 계측 결과 처리 화면 전화 기능 추가(#128)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project/sinabro/ObjectDetectionActivity.kt
  app/src/main/java/com/project/sinabro/PlayActivity.java
  app/src/main/res/layout/activity_modifiy_register_headcount.xml
Labels: ⚙ FEAT

#131 [refactor]: MainActivity 내 불필요한 코드 제거(#130)
  app/src/main/java/com/project/sinabro/MainActivity.java
Labels: ⛓ REFACTOR
